#!/bin/zsh

exitfn () {
    trap SIGINT
    echo; echo 'Aarghh!!'
#    docker-compose down
    docker-compose rm -f
    docker rmi "$(docker images -f "dangling=true" -q)"
    exit
}

trap "exitfn" INT            # Set up SIGINT trap to call function.


docker-compose build --force-rm
docker-compose up --no-build

